<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHSP9xhB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHSP9xhB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHSP9xhB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHSP9xhB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHSP9xhB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HSP9xhB',
    'container.build_id' => '72ac2111',
    'container.build_time' => 1586861430,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHSP9xhB');
